### ISSUE TITLE
Util Loggin LogLevel could not be updated

### ISSUE THREAD

**Issue by r-hannuschka** [q2g/daVinci.js#90]
It's not possible to update / change a logging level for a Class only the initial value is used.

```
const logger = new Logger('MySpace');

// set logging level to warnings ( error, fatal ) no debug messages
logging.setLogLevel('MySpace', logging.LogLevel.warn);
logger.logError('oh no an error occoured'); // works

// update logging level to get debug messages
logging.setLogLevel('MySpace', logging.LogLevel.debug);
logger.debug('my value is nice');
```

Expected: 
   warning message is displayed into console
   debug message "my value is nice" is displayed into console

What happens: 
  only warning message will be displayed

It is explained very simple, since setLogLevel only pushes a new value into an Array so we have multiple log Levels for same class in 1 Array, but on the other side if he try to get a log level for a key he returns the first value we have set.  

The initial value determines what can be logged.

**Comment by r-hannuschka** [comment]
fixed with cb33583e3282c9edc23833c1305e9d5eb3c45057

**Comment by r-hannuschka** [comment]
should work now

**Comment by konne** [comment]
@r-hannuschka should is no answer for an issue -> in the future please add a test and than you can easy write closed

**Comment by r-hannuschka** [comment]
added unit tests, test it directly and it was working for me ;)
